version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: SeconAPI.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=secon_db;Username=postgres;Password=postgres;
      - PythonServiceUri=http://127.0.0.1:5001/batch-process
    networks:
      - secon-network



  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secon-network


   frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile : Dockerfile
      ports:
        - "80:5173"
      networks:
        - app_network



  
networks:
  secon-network:
    driver: bridge

volumes:
  postgres_data