version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: SeconAPI.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
      - python_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=secon_db;Username=postgres;Password=postgres;
      - PythonServiceUri=http://python_service:5001/process
    networks:
      - secon-network



  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secon-network



  python_service:
     build:
       context: ./python_service
       dockerfile: Dockerfile
     ports:
       - "5001:5001"

  
networks:
  secon-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: